<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "diskographie"
 *
 * Auto generated by Extension Builder 2015-01-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Discography',
	'description' => '',
	'category' => 'misc',
	'author' => 'Markus Pircher',
	'author_email' => 'markus.pircher@netzolutions.eu',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'lyrics' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);